name: CD to Oracle VM

on:
  push:
    branches:
      - master  # master 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. SSH 키 설정
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}  # GitHub Secrets에 저장된 개인 키
          known_hosts: ${{ secrets.SSH_HOST }}  # Oracle VM의 IP 또는 도메인

      # 3. Oracle VM에 배포
      - name: Deploy to Oracle VM
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}  # GitHub Secrets에 저장된 호스트
          SSH_USER: ubuntu  # SSH 사용자
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $SSH_USER@$SSH_HOST << 'EOF'
            cd API_BE &&
            git pull origin master
          EOF

      # 4. docker compose 실행
      - name: Deploy Application
        run: |
          docker compose pull &&
          docker compose up -d --build
        working-directory: ./Sportagram
